### PR TITLE
add New Math Courses for Data Science

### PR DESCRIPTION
**Pull request by aminkhalaf**
Add Math Courses to Read me file

### CODE REVIEW

**Comment by amrrs** [comment]
Thanks for the PR. Was this copied from somewhere or Did you collate it?

**Comment by aminkhalaf** [comment]
I wrote my courses that I studied and copied some others

**Comment by amrrs** [comment]
Hey @aminkhalaf  Thanks for the comment. This has a conflict now, Can you please edit your PR?

**Comment by aminkhalaf** [comment]
Sure give me a second

**Comment by amrrs** [comment]
I think that could be because you've already forked this so you might have to locally merge it

**Pull request closed without merging**
